import openai
import json
import yaml
from typing import List, Dict, Any, Optional
from pathlib import Path
from .config import Settings


class AIGenerator:
    def __init__(self):
        self.client = openai.OpenAI(
            api_key=Settings.DEEPSEEK_API_KEY,
            base_url="https://api.deepseek.com"
        )
        self.framework_templates = {
            "react": {
                "package.json": {
                    "name": "generated-app",
                    "version": "1.0.0",
                    "private": True,
                    "dependencies": {
                        "react": "^18.2.0",
                        "react-dom": "^18.2.0",
                        "axios": "^1.6.0",
                        "tailwindcss": "^3.3.0"
                    },
                    "scripts": {
                        "start": "react-scripts start",
                        "build": "react-scripts build",
                        "test": "react-scripts test",
                        "eject": "react-scripts eject"
                    }
                },
                "src/index.js": """import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);"""
            },
            "vue": {
                "package.json": {
                    "name": "generated-app",
                    "version": "1.0.0",
                    "private": True,
                    "dependencies": {
                        "vue": "^3.3.0",
                        "axios": "^1.6.0"
                    }
                }
            },
            "svelte": {
                "package.json": {
                    "name": "generated-app",
                    "version": "1.0.0",
                    "private": True,
                    "dependencies": {
                        "svelte": "^4.2.0"
                    }
                }
            }
        }

    async def generate_full_project(self, requests: List[Dict], design_tokens: Dict, framework="react") -> Dict[str, str]:
        """生成完整的项目文件"""
        prompt = f"""你是一个资深前端开发工程师。根据以下网络请求和设计 token，生成一个完整的 {framework} 项目。

要求：
1. 包含 package.json、src/App.jsx、src/index.js 等文件。
2. 实现页面布局，使用设计 token 定义样式。
3. 根据请求创建 API 服务层，使用 mock 数据。
4. 处理交互逻辑。
5. 代码必须可直接运行。

网络请求示例：
{json.dumps(requests[:10], indent=2)}

设计 token：
{json.dumps(design_tokens, indent=2)}

请返回 JSON 格式，键为文件路径，值为文件内容。
例如：{{"package.json": "...", "src/App.jsx": "..."}}
"""
        try:
            response = self.client.chat.completions.create(
                model="deepseek-chat",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                max_tokens=8000,
                response_format={"type": "json_object"}
            )
            result = json.loads(response.choices[0].message.content)
            # 确保包含必要的模板文件
            if "package.json" not in result:
                result["package.json"] = json.dumps(self.framework_templates.get(framework, {}).get("package.json", {}), indent=2)
            return result
        except Exception as e:
            # 回退到模板生成
            return self._generate_fallback_project(requests, design_tokens, framework)

    def _generate_fallback_project(self, requests: List[Dict], design_tokens: Dict, framework: str) -> Dict[str, str]:
        """当AI生成失败时，生成一个基础项目"""
        base_files = {}
        if framework == "react":
            base_files = {
                "package.json": json.dumps(self.framework_templates["react"]["package.json"], indent=2),
                "src/App.jsx": self._generate_react_app(requests, design_tokens),
                "src/index.js": self.framework_templates["react"]["src/index.js"],
                "src/index.css": self._generate_css(design_tokens),
                "src/api.js": self._generate_api_service(requests),
                "README.md": "# Generated Project\n\nThis project was auto-generated by WebScribe."
            }
        return base_files

    def _generate_react_app(self, requests: List[Dict], design_tokens: Dict) -> str:
        """生成React App组件"""
        endpoints = [req for req in requests if req.get("method") in ["GET", "POST"]]
        endpoint_list = "\n".join([f"// {req['method']} {req['url']}" for req in endpoints[:5]])
        return f"""import React, {{ useState }} from 'react';
import './index.css';
import {{ fetchData }} from './api';

function App() {{
  const [data, setData] = useState(null);

  const handleClick = async () => {{
    const result = await fetchData();
    setData(result);
  }};

  return (
    <div className="app">
      <header className="header">
        <h1>Generated Application</h1>
        <p>Auto-generated from WebScribe exploration</p>
      </header>
      <main className="main">
        <button className="btn" onClick={{handleClick}}>
          Fetch Data
        </button>
        {{data && (
          <pre className="data-preview">
            {{JSON.stringify(data, null, 2)}}
          </pre>
        )}}
        <div className="endpoints">
          <h3>Captured Endpoints:</h3>
          <pre>{endpoint_list}</pre>
        </div>
      </main>
    </div>
  );
}}

export default App;
"""

    def _generate_api_service(self, requests: List[Dict]) -> str:
        """生成API服务文件"""
        endpoints = []
        for req in requests[:10]:
            if req.get("method") in ["GET", "POST", "PUT", "DELETE"]:
                endpoints.append(req)

        mock_responses = []
        for i, req in enumerate(endpoints[:5]):
            mock_responses.append(f"""
  // Mock for {req['method']} {req['url']}
  if (url.includes('{req['url'].split('/')[-1]}')) {{
    return Promise.resolve({{
      status: 200,
      data: {{ message: "Mock response for {req['method']} {req['url']}" }}
    }});
  }}""")

        return f"""import axios from 'axios';

const API_BASE = 'https://api.example.com';

export const fetchData = async () => {{
  try {{
    const response = await axios.get(API_BASE + '/data');
    return response.data;
  }} catch (error) {{
    console.error('Error fetching data:', error);
    return {{ error: true }};
  }}
}};

export const mockRequest = async (url, method = 'GET', data = null) => {{
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 300));
  {''.join(mock_responses)}
  return Promise.resolve({{
    status: 200,
    data: {{ message: "Default mock response" }}
  }});
}};
"""

    def _generate_css(self, design_tokens: Dict) -> str:
        """生成CSS文件"""
        colors = design_tokens.get('colors', {})
        fonts = design_tokens.get('fonts', {})
        font_sizes = design_tokens.get('font_sizes', {})
        border_radius = design_tokens.get('border_radius', {})

        css_vars = []
        for name, value in colors.items():
            css_vars.append(f"  --color-{name}: {value};")
        for name, value in fonts.items():
            css_vars.append(f"  --font-{name}: {value};")
        for name, value in font_sizes.items():
            css_vars.append(f"  --font-size-{name}: {value}px;")
        for name, value in border_radius.items():
            css_vars.append(f"  --border-radius-{name}: {value}px;")

        return f""":root {{
{chr(10).join(css_vars)}
}}

* {{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}}

body {{
  font-family: var(--font-primary, 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif);
  background-color: var(--color-background, #f5f5f5);
  color: var(--color-text, #333);
}}

.app {{
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}}

.header {{
  text-align: center;
  margin-bottom: 3rem;
  padding: 2rem;
  background: var(--color-primary, #007bff);
  color: white;
  border-radius: var(--border-radius-large, 12px);
}}

.btn {{
  padding: 0.75rem 1.5rem;
  background: var(--color-primary, #007bff);
  color: white;
  border: none;
  border-radius: var(--border-radius-medium, 8px);
  cursor: pointer;
  font-size: 1rem;
  transition: opacity 0.2s;
}}

.btn:hover {{
  opacity: 0.9;
}}

.data-preview {{
  background: white;
  padding: 1rem;
  border-radius: var(--border-radius-medium, 8px);
  margin-top: 1rem;
  overflow-x: auto;
}}

.endpoints {{
  margin-top: 2rem;
  padding: 1rem;
  background: #f8f9fa;
  border-radius: var(--border-radius-medium, 8px);
}}
"""

    async def generate_openapi_spec(self, requests: List[Dict]) -> Dict[str, Any]:
        """生成OpenAPI 3.0规范"""
        paths = {}
        for req in requests:
            if not req.get("url") or not req.get("method"):
                continue
            # 简化URL作为路径
            path = self._normalize_path(req["url"])
            method = req["method"].lower()
            if path not in paths:
                paths[path] = {}
            
            paths[path][method] = {
                "summary": f"Auto-generated from {req['url']}",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "example": req.get("post_data") or {"message": "Mock response"}
                            }
                        }
                    }
                }
            }
            if req.get("post_data"):
                paths[path][method]["requestBody"] = {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": self._infer_schema(req["post_data"])
                            }
                        }
                    }
                }

        spec = {
            "openapi": "3.0.0",
            "info": {
                "title": "WebScribe Generated API",
                "version": "1.0.0",
                "description": "Auto-generated from captured network requests"
            },
            "paths": paths
        }
        return spec

    def _normalize_path(self, url: str) -> str:
        """将URL转换为OpenAPI路径格式"""
        # 简单实现：提取路径部分
        from urllib.parse import urlparse
        parsed = urlparse(url)
        path = parsed.path
        if not path:
            path = "/"
        # 将数字ID替换为{id}
        import re
        path = re.sub(r'/\d+', '/{id}', path)
        return path

    def _infer_schema(self, data: Any) -> Dict:
        """推断JSON数据的schema"""
        if isinstance(data, dict):
            return {k: {"type": type(v).__name__} for k, v in data.items()}
        return {"value": {"type": type(data).__name__}}

    async def generate_design_system_css(self, design_tokens: Dict) -> str:
        """生成设计系统CSS变量文件"""
        return self._generate_css(design_tokens)

    async def generate_html_report(self, task_id: int, config: Dict, stats: Dict) -> str:
        """生成HTML报告"""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WebScribe Report - Task {task_id}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 0; padding: 2rem; background: #f9f9f9; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 2rem; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 0.5rem; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 2rem 0; }}
        .stat-card {{ background: #f8f9fa; padding: 1.5rem; border-radius: 8px; text-align: center; }}
        .stat-value {{ font-size: 2rem; font-weight: bold; color: #3498db; }}
        .section {{ margin: 2rem 0; }}
        pre {{ background: #2c3e50; color: #ecf0f1; padding: 1rem; border-radius: 6px; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>WebScribe Exploration Report</h1>
        <p><strong>Task ID:</strong> {task_id}</p>
        <p><strong>Start URL:</strong> {config.get('start_url', 'N/A')}</p>
        <p><strong>Exploration Time:</strong> {stats.get('timestamp', 'N/A')}</p>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value">{stats.get('pages_visited', 0)}</div>
                <div class="stat-label">Pages Visited</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{stats.get('requests_captured', 0)}</div>
                <div class="stat-label">Requests Captured</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{stats.get('screenshots', 0)}</div>
                <div class="stat-label">Screenshots</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{stats.get('performance_score', 'N/A')}</div>
                <div class="stat-label">Performance Score</div>
            </div>
        </div>

        <div class="section">
            <h2>Generated Artifacts</h2>
            <ul>
                <li><strong>Frontend Code:</strong> React project with mock API</li>
                <li><strong>OpenAPI Specification:</strong> API documentation in OpenAPI 3.0 format</li>
                <li><strong>Design System:</strong> CSS variables extracted from the site</li>
                <li><strong>Responsive CSS:</strong> Media queries for mobile adaptation</li>
                <li><strong>State Graph:</strong> Mermaid diagram of page transitions</li>
            </ul>
        </div>

        <div class="section">
            <h2>Next Steps</h2>
            <p>Download the generated ZIP file and extract it. Run the following commands to start the generated application:</p>
            <pre>cd generated_code
npm install
npm start</pre>
        </div>
    </div>
</body>
</html>"""

    async def generate_component(self, description: str, framework="react") -> str:
        """生成单个组件"""
        prompt = f"生成一个 {framework} 组件：{description}，返回完整的组件代码，包含样式和必要的 imports。"
        response = self.client.chat.completions.create(
            model="deepseek-chat",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2000
        )
        return response.choices[0].message.content